### PR TITLE
16 fix gamestate

### LINKED ISSUE #16: Fix GameState
GameState does not reset after each match

Proposed solution:

- [x] make GameState local

### PR DESCRIPTION
**Pull request by u413-284-si**
- move GameState as local variable into renderGame()
- passe GameState as argument to all dependent functions
- remove unused files/code
- fix minor code structure inconsistencies

closes #16

### CODE REVIEW

**Review by gwolf-011235 — CHANGES_REQUESTED** [review]
Passing around GameState as type any defeats the purpose of _Type_ script.

Right now _interface_ would be a good fit, which is like a blob of data.

We could also create a _class_ Gamestate and absorb functions into it --> e.g. resetBall could be a method of GameState

**Comment by u413-284-si** [comment]
Introduced interface for typing of GameState

File: app/frontend/src/IGameState.ts
Comment (gwolf-011235) [inline app/frontend/src/IGameState.ts:1]: P3: move into folder "src/types"

File: app/frontend/src/game.ts [hunk 1]
```diff
@@ -14,80 +14,86 @@ export function renderGame() {
...
-
-	startGame(canvas);
-	gameLoop(canvas, ctx);
-}
-
-function gameLoop(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
-	update(canvas);
-	draw(canvas, ctx);
-	requestAnimationFrame(() => gameLoop(canvas, ctx));
+	const gameState: IGameState = {
```
Comment (gwolf-011235) [inline app/frontend/src/game.ts:17]: P3: would extract into function "initGameState"

File: app/frontend/src/game.ts [hunk 2]
```diff
@@ -14,80 +14,86 @@ export function renderGame() {
...
 }
 
-export function startGame(canvas: HTMLCanvasElement) {
-	GameState.gameOver = false;
-	GameState.gameStarted = true;
-	GameState.initialize(canvas.width, canvas.height);
-
-	resetGame(canvas);
+function startGame(canvas: HTMLCanvasElement,  ctx: CanvasRenderingContext2D, gameState: IGameState) {
+	gameState.gameOver = false;
```
Comment (gwolf-011235) [inline app/frontend/src/game.ts:40]: P2: can be removed, already set in init

**Review by gwolf-011235 — APPROVED** [review]
Lookin good.

Just some P3s

File: app/frontend/src/IGameState.ts
Comment (u413-284-si) [reply app/frontend/src/IGameState.ts:1]: done

File: app/frontend/src/game.ts (hunk 1 above)
Comment (u413-284-si) [reply app/frontend/src/game.ts]: done

File: app/frontend/src/game.ts (hunk 2 above)
Comment (u413-284-si) [reply app/frontend/src/game.ts:43]: left for restarting a new game after hitting Enter at end of finished game. Dunno how you implemented it in your branch. Leaving it and can be overwritten by your changes
